name: DungeonSystem
main: com.littlesquad.Main
api-version: 1.21.7
version: 1.0
commands:
  dungeon:
    description: a
    aliases: dg
depend:
  - PlaceholderAPI
  - MMOCore
  - MMOItems
  - MythicLib